// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStation(arg1) {
  return window['go']['main']['App']['GetStation'](arg1);
}

export function GetStations() {
  return window['go']['main']['App']['GetStations']();
}
