// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStation(arg1:string):Promise<main.Station>;

export function GetStations():Promise<{[key: string]: main.Station}>;
